### ISSUE TITLE
[FRQ] Support horizontal scaling or cluster

### ISSUE THREAD

**Issue by jackbit** [HanzHaxors/fabuya#4]
Hi buddy,

Thank you for the insight and idea, I want to discuss future request to use redis or firestore to support horizontal scaling

**Is your feature request related to a problem? Please describe.**
I want to have cluster  or autoscaling whatsapp multidevice, but right now the baileys only use local file to save auth state and save the instance in memory process

**Describe the solution you'd like**
To implement horizontal scaling with shared session between cluster or server, I think it's good to have option to replace auth state file to redis or firestore

**Comment by HanzCEO** [comment]
Thanks for your feature request,

However, due to my personal limitation i can't implement this feature for you.
But, you can implement this yourself and i can show you how.

**This is how i will resolve your issue**
My implementation of `AuthSave` and Storages will be documented deeply
with handful of example codes.

> Hanz

**Comment by HanzCEO** [comment]
Hello, i have released an update. Install them using
```sh
npm install fabuya@beta
```

More on that [here](https://github.com/HanzHaxors/fabuya/tree/main/docs#installation)

**Comment by HanzCEO** [comment]
Archived. Someday, i will implement this as an addon/extension.
